import { useEffect, useMemo, useState } from "react";
import { BrowserRouter, Link, NavLink, Navigate, Outlet, Route, Routes, useNavigate, useParams } from "react-router-dom";
import "./App.css";
import InsightsPage from "./pages/Insights";
import ProfilePage from "./pages/Profile";
import SettingsPage from "./pages/Settings";
import api, { setAuthToken } from "./utils/api";

const msg = (e) => { const d = e?.response?.data?.detail ?? e?.response?.data ?? e?.message; return Array.isArray(d) ? d.map(x => x.msg || String(x)).join(" · ") : typeof d === "object" ? d?.message || JSON.stringify(d) : d || "Something went wrong."; };
const date = (v) => v ? new Date(v).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "—";
const docPath = (id) => `/documents/${id}`;

export default function App() {
  const [token, setToken] = useState(() => localStorage.getItem("documind_token") || "");
  const [theme, setTheme] = useState(() => localStorage.getItem("documind_theme") || "light");
  useEffect(() => setAuthToken(token), [token]);
  useEffect(() => { document.body.dataset.theme = theme; localStorage.setItem("documind_theme", theme); }, [theme]);
  return <BrowserRouter><Routes>
    <Route path="/" element={<Landing token={token} />} />
    <Route path="/login" element={<Public token={token}><Auth setToken={setToken} /></Public>} />
    <Route path="/register" element={<Public token={token}><Auth register setToken={setToken} /></Public>} />
    <Route element={<Protected token={token}><Layout setToken={setToken} /></Protected>}>
      <Route path="/dashboard" element={<Dashboard />} /><Route path="/documents" element={<Documents />} />
      <Route path="/documents/:documentId" element={<DocumentDetail />} /><Route path="/insights" element={<InsightsPage />} />
      <Route path="/profile" element={<ProfilePage />} /><Route path="/settings" element={<SettingsPage theme={theme} setTheme={setTheme} />} />
    </Route>
    <Route path="*" element={<Navigate to={token ? "/dashboard" : "/"} replace />} />
  </Routes></BrowserRouter>;
}
function Protected({ token, children }) { return token ? children : <Navigate to="/login" replace />; }
function Public({ token, children }) { return token ? <Navigate to="/dashboard" replace /> : children; }
function Layout({ setToken }) {
  const navigate = useNavigate(); const logout = async () => { try { await api.post("/auth/logout"); } catch {} setAuthToken(""); setToken(""); navigate("/login", { replace: true }); };
  return <div className="dashboard-layout"><aside className="sidebar"><Link to="/dashboard" className="sidebar-brand">DOCUMIND<span>Document intelligence</span></Link><nav className="sidebar-nav">{[["/dashboard","Dashboard"],["/documents","My Documents"],["/insights","DocuMind Insights"],["/profile","Profile"],["/settings","Settings"]].map(([to,label]) => <NavLink key={to} to={to} className={({isActive}) => `nav-link${isActive ? " active" : ""}`}>{label}</NavLink>)}</nav><button className="logout-button" onClick={logout}>Logout</button></aside><main className="dashboard-content"><Outlet /></main></div>;
}
function Landing({ token }) { return <div className="landing-page"><nav className="topbar"><Link className="brand" to="/">DocuMind</Link><div className="nav-actions"><Link className="button secondary" to={token ? "/dashboard" : "/login"}>Login</Link><Link className="button primary" to={token ? "/dashboard" : "/register"}>Get Started</Link></div></nav><main className="hero-section"><div className="hero-copy"><span className="eyebrow">Document intelligence platform</span><h1>Turn your documents into knowledge.</h1><p>Understand every document in your collection. Ask natural-language questions, get grounded answers with source references, and uncover the ideas that connect your files.</p><div className="cta-row"><Link to="/register" className="button primary large">Get Started</Link><Link to="/login" className="button secondary large">Login</Link></div></div><div className="hero-panel"><Card title="Grounded Q&A" text="Answers from your own documents, with matching source references."/><Card title="Collection discovery" text="Topics, relationships, clustering, and anomaly detection."/><Card title="Knowledge graph" text="See the structure and themes across your document library."/></div></main><div className="capability-strip">Document understanding · Q&A · summaries · topic discovery · relationships · clustering · anomaly detection · knowledge graph · analytics</div></div>; }
function Card({ title, text }) { return <article className="mini-card"><strong>{title}</strong><span>{text}</span></article>; }
function Auth({ register, setToken }) {
  const nav = useNavigate(); const [form,setForm] = useState(register ? { full_name:"", username:"", email:"", password:"" } : { email:"", password:"" }); const [error,setError] = useState(""); const [loading,setLoading] = useState(false);
  const field = (label,name,type="text") => <label>{label}<input type={type} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})} required minLength={name==="password" ? 6 : undefined}/></label>;
  const submit = async e => { e.preventDefault(); setLoading(true); setError(""); try { if (register) await api.post("/auth/register",form); const r=await api.post("/auth/login",{email:form.email,password:form.password}); setAuthToken(r.data.access_token); setToken(r.data.access_token); nav("/dashboard",{replace:true}); } catch(e) { setError(msg(e)); } finally { setLoading(false); } };
  return <div className="auth-page"><div className="auth-card"><Link className="auth-brand" to="/">DocuMind</Link><span className="eyebrow">{register ? "Start discovering" : "Welcome back"}</span><h2>{register ? "Create your workspace" : "Login to DocuMind"}</h2><form className="auth-form" onSubmit={submit}>{register && <>{field("Full name","full_name")}{field("Username","username")}</>}{field("Email","email","email")}{field("Password","password","password")}{error && <div className="error-box">{error}</div>}<button className="button primary wide" disabled={loading}>{loading ? "Please wait…" : register ? "Create account" : "Login"}</button></form><p className="auth-link">{register ? "Already have an account?" : "New to DocuMind?"} <Link to={register ? "/login" : "/register"}>{register ? "Login" : "Register"}</Link></p></div></div>;
}
function Empty({ text, to, action }) { return <div className="empty-state"><p>{text}</p>{to && <Link to={to} className="button secondary small">{action}</Link>}</div>; }
function Dashboard() {
  const [stats,setStats]=useState(null),[docs,setDocs]=useState([]),[error,setError]=useState("");
  useEffect(()=>{Promise.all([api.get("/documents/stats"),api.get("/documents")]).then(([s,d])=>{setStats(s.data);setDocs(d.data);}).catch(e=>setError(msg(e)));},[]);
  return <><header className="page-header"><div><span className="eyebrow">Your workspace</span><h1>Knowledge, ready to explore.</h1><p>Upload documents, ask grounded questions, and find what connects them.</p></div><Link className="button primary" to="/documents">Upload Document</Link></header>{error&&<div className="error-box">{error}</div>}<section className="stats-grid">{[["Total Documents",stats?.total_documents],["Total Pages",stats?.total_pages],["Total Words",stats?.total_words],["Total Questions",stats?.total_questions]].map(([l,v])=><article className="stat-card" key={l}><span>{l}</span><strong>{v??"—"}</strong></article>)}</section><section className="panel-grid"><article className="panel"><div className="panel-title"><h3>Recent Documents</h3><Link to="/documents">My Documents</Link></div>{docs.length?<div className="document-list">{docs.slice(0,5).map(d=><Link className="document-item" key={d.id} to={docPath(d.id)}><div><strong>{d.title}</strong><p>{d.page_count} pages · {d.word_count.toLocaleString()} words · {date(d.upload_date)}</p></div><span className="status-pill">{d.processing_status}</span></Link>)}</div>:<Empty text="No documents yet. Upload a PDF to begin building your knowledge base." to="/documents" action="Upload Document"/>}</article><article className="panel action-panel"><h3>Explore your collection</h3><p>See relationships, key topics, clusters, trends, outliers, and a knowledge graph derived from your real documents.</p><Link className="button secondary" to="/insights">Explore DocuMind Insights</Link></article></section></>;
}
function Documents() {
  const [docs,setDocs]=useState([]),[files,setFiles]=useState([]),[query,setQuery]=useState(""),[sort,setSort]=useState("newest"),[uploading,setUploading]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const load=()=>api.get("/documents").then(r=>setDocs(r.data)).catch(e=>setError(msg(e))); useEffect(()=>{load();},[]);
  const upload=async()=>{if(!files.length)return;setUploading(true);setError("");setNotice("");const results=await Promise.allSettled(files.map(file=>{const f=new FormData();f.append("file",file);return api.post("/documents/upload",f);}));const failed=results.filter(r=>r.status==="rejected");if(failed.length)setError(`${failed.length} upload(s) could not be processed: ${msg(failed[0].reason)}`);else setNotice(`${files.length} document(s) processed successfully.`);setFiles([]);setUploading(false);load();};
  const remove=async id=>{if(!window.confirm("Delete this document and its chat history?"))return;try{await api.delete(docPath(id));setDocs(x=>x.filter(d=>d.id!==id));}catch(e){setError(msg(e));}};
  const shown=useMemo(()=>docs.filter(d=>d.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):new Date(b.upload_date)-new Date(a.upload_date)),[docs,query,sort]);
  return <><header className="page-header"><div><span className="eyebrow">Document library</span><h1>My Documents</h1><p>Upload PDFs and turn each into an answerable source of knowledge.</p></div></header><section className="panel upload-panel"><h3>Upload Document</h3><div className="upload-box"><input aria-label="Upload PDF files" type="file" accept="application/pdf,.pdf" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><button className="button primary" disabled={!files.length||uploading} onClick={upload}>{uploading?"Processing…":"Upload & Process"}</button></div>{files.length>0&&<p className="selected-files">Selected: {files.map(f=>f.name).join(", ")}</p>}{notice&&<div className="success-box">{notice}</div>}{error&&<div className="error-box">{error}</div>}</section><div className="toolbar-row"><div className="search-box"><input placeholder="Search documents" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="title">Title A–Z</option></select></div>{shown.length?<section className="document-card-grid">{shown.map(d=><article className="document-card" key={d.id}><div className="document-card-top"><div className="pdf-icon">PDF</div><span className="status-pill">{d.processing_status}</span></div><div><h3>{d.title}</h3><div className="meta-list"><span>Uploaded {date(d.upload_date)}</span><span>{d.page_count} pages · {d.word_count.toLocaleString()} words</span></div></div><div className="card-actions"><Link to={docPath(d.id)} className="button secondary small">Open</Link><Link to={docPath(d.id)} className="button secondary small">Ask</Link><button className="button danger small" onClick={()=>remove(d.id)}>Delete</button></div></article>)}</section>:<div className="panel"><Empty text={docs.length?"No documents match your search.":"Your document library is empty."}/></div>}</>;
}
function DocumentDetail() {
  const {documentId}=useParams();const [doc,setDoc]=useState(null),[chunks,setChunks]=useState([]),[chat,setChat]=useState([]),[question,setQuestion]=useState(""),[summary,setSummary]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{setError("");Promise.all([api.get(docPath(documentId)),api.get(`${docPath(documentId)}/chunks`),api.get(`${docPath(documentId)}/chat`)]).then(([d,c,h])=>{setDoc(d.data);setChunks(c.data);setChat(h.data);}).catch(e=>setError(msg(e)));},[documentId]);
  const ask=async e=>{e.preventDefault();if(!question.trim())return;setBusy(true);setError("");try{const r=await api.post(`${docPath(documentId)}/ask`,{question:question.trim()});setChat(x=>[...x,r.data]);setQuestion("");}catch(e){setError(msg(e));}finally{setBusy(false);}};
  const makeSummary=async()=>{setBusy(true);setError("");try{const r=await api.post(`${docPath(documentId)}/summary`);setSummary(r.data);}catch(e){setError(msg(e));}finally{setBusy(false);}};
  if(error&&!doc)return <div className="error-box">{error}</div>;if(!doc)return <div className="panel loading-box">Loading document workspace…</div>;
  return <><header className="page-header document-heading"><div><Link className="back-link" to="/documents">← My Documents</Link><h1>{doc.title}</h1><p>Document workspace</p></div><span className="status-pill">{doc.processing_status}</span></header>{error&&<div className="error-box">{error}</div>}<section className="details-layout"><article className="panel"><h3>Document metadata</h3><div className="details-grid"><div><label>Pages</label><strong>{doc.page_count}</strong></div><div><label>Words</label><strong>{doc.word_count.toLocaleString()}</strong></div><div><label>Chunks</label><strong>{chunks.length}</strong></div><div><label>Uploaded</label><strong>{date(doc.upload_date)}</strong></div></div><button className="button secondary" onClick={makeSummary} disabled={busy}>{busy?"Working…":"Generate Summary"}</button>{(summary||doc.summary)&&<div className="summary-box"><h4>Summary & key points</h4><p>{summary?.executive_summary||doc.summary}</p>{summary?.key_points?.length>0&&<ul>{summary.key_points.map((x,i)=><li key={i}>{x}</li>)}</ul>}</div>}</article><article className="panel text-preview-panel"><h3>Extracted text preview</h3><pre>{doc.extracted_text||"No extractable text was found in this PDF."}</pre></article></section><section className="workspace-grid"><article className="panel chat-panel"><h3>Ask DocuMind</h3><p className="muted">Answers are grounded in your uploaded documents and include matching source excerpts.</p><div className="chat-history">{chat.length?chat.map((m,i)=><article className="chat-message" key={m.id||i}><strong>You</strong><p>{m.question}</p><strong>DocuMind</strong><p>{m.answer}</p>{m.sources?.length>0&&<div className="source-list">{m.sources.map((s,j)=><details key={j}><summary>{s.document_name || "Source"} · page {s.page_number}{s.similarity_score != null ? ` · similarity ${(s.similarity_score * 100).toFixed(0)}%` : ""}</summary><p>{s.snippet}</p></details>)}</div>}</article>):<Empty text="Ask a question to start a grounded conversation with this document."/ >}</div><form className="chat-input-row" onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a question about this document"/><button className="button primary" disabled={busy}>{busy?"Asking…":"Ask"}</button></form></article><article className="panel"><h3>Document chunks</h3><p className="muted">{chunks.length} indexed sections available for retrieval.</p><div className="chunk-list">{chunks.slice(0,6).map(c=><details key={c.id}><summary>Page {c.page_number} · Section {c.chunk_index+1}</summary><p>{c.text}</p></details>)}</div></article></section></>;
}
